const logo = "assets/images/shaghaf_logo.png";
const backGroundImage = "assets/images/splash_screen.svg";
const advertisementImage = "assets/images/advertisement.png";
const workingSpace = "assets/images/co-vorking space.png";
const room = "assets/images/Game day-amico 2.png";
const order = "assets/images/Ecommerce web page-amico 1.png";
const events = "assets/images/Prototyping process-amico (1) 3.png";
const trainingRoom = "assets/images/Training room.jpeg";
const frame = "assets/images/Frame 30042.png";
